package com.devson.nvplayer.ui.theme

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

//  Built-in theme palette catalogue
//  Each entry is a human-visible name + two complete Material 3 ColorSchemes
//  (one for light mode, one for dark mode).  Only accent/primary colours differ
//  between palettes; the neutral surface/background tokens stay consistent so
//  the app layout always feels coherent.

enum class AppThemePalette(
    val displayName: String,
    // preview swatches shown in the picker card (light/dark primary & secondary)
    val lightPrimary: Color,
    val darkPrimary: Color,
    val lightSecondary: Color,
    val darkSecondary: Color
) {
    CINEMATIC(
        displayName    = "Cinematic",
        lightPrimary   = Color(0xFF00BCD4),
        darkPrimary    = Color(0xFF80EEFF),
        lightSecondary = Color(0xFFFFB300),
        darkSecondary  = Color(0xFFFFE082)
    ),
    BLUE(
        displayName    = "Nosved Blue",
        lightPrimary   = Color(0xFF1A73E8),
        darkPrimary    = Color(0xFFAEC6FF),
        lightSecondary = Color(0xFF3949AB),
        darkSecondary  = Color(0xFFC5CAE9)
    ),
    EMERALD(
        displayName    = "Emerald",
        lightPrimary   = Color(0xFF00897B),
        darkPrimary    = Color(0xFF80CBC4),
        lightSecondary = Color(0xFF43A047),
        darkSecondary  = Color(0xFFA5D6A7)
    ),
    SUNSET(
        displayName    = "Sunset",
        lightPrimary   = Color(0xFFE64A19),
        darkPrimary    = Color(0xFFFF8A65),
        lightSecondary = Color(0xFFF9A825),
        darkSecondary  = Color(0xFFFFE082)
    ),
    ROSE(
        displayName    = "Rose",
        lightPrimary   = Color(0xFFD81B60),
        darkPrimary    = Color(0xFFF48FB1),
        lightSecondary = Color(0xFF8E24AA),
        darkSecondary  = Color(0xFFCE93D8)
    ),
    MIDNIGHT(
        displayName    = "Midnight",
        lightPrimary   = Color(0xFF3949AB),
        darkPrimary    = Color(0xFFB0BEC5),
        lightSecondary = Color(0xFF607D8B),
        darkSecondary  = Color(0xFFCFD8DC)
    );

    // Color Schemes

    fun lightScheme(): ColorScheme = when (this) {

        CINEMATIC -> lightColorScheme(
            primary                = Color(0xFF00BCD4),
            onPrimary              = Color.White,
            primaryContainer       = Color(0xFFB2EBF2),
            onPrimaryContainer     = Color(0xFF006978),
            secondary              = Color(0xFFFFB300),
            onSecondary            = Color(0xFF1A1200),
            secondaryContainer     = Color(0xFFFFECB3),
            onSecondaryContainer   = Color(0xFF201B00),
            tertiary               = Color(0xFF7C4DFF),
            onTertiary             = Color.White,
            tertiaryContainer      = Color(0xFFEDE0FF),
            onTertiaryContainer    = Color(0xFF21005E),
            error                  = Color(0xFFCF6679),
            onError                = Color.White,
            errorContainer         = Color(0xFFFFDAD6),
            onErrorContainer       = Color(0xFF410002),
            background             = Color(0xFFF0F4F8),
            onBackground           = Color(0xFF0D1117),
            surface                = Color(0xFFFFFFFF),
            onSurface              = Color(0xFF0D1117),
            surfaceVariant         = Color(0xFFE8EDF4),
            onSurfaceVariant       = Color(0xFF444F5C),
            outline                = Color(0xFFB0BAC8),
            outlineVariant         = Color(0xFFD0D8E4),
            inverseSurface         = Color(0xFF2A3340),
            inverseOnSurface       = Color(0xFFF0F4F8),
            inversePrimary         = Color(0xFF80EEFF),
            surfaceContainerLowest = Color(0xFFFAFCFF),
            surfaceContainerLow    = Color(0xFFF0F4F8),
            surfaceContainer       = Color(0xFFE3EAEF),
            surfaceContainerHigh   = Color(0xFFFFFFFF),
            surfaceContainerHighest= Color(0xFFFFFFFF),
            scrim                  = Color(0xFF000000)
        )

        BLUE -> lightColorScheme(
            primary                = Color(0xFF1A73E8),
            onPrimary              = Color.White,
            primaryContainer       = Color(0xFFDAE2FF),
            onPrimaryContainer     = Color(0xFF0D47A1),
            secondary              = Color(0xFF3949AB),
            onSecondary            = Color.White,
            secondaryContainer     = Color(0xFFE0E5FF),
            onSecondaryContainer   = Color(0xFF001587),
            tertiary               = Color(0xFF1E8E3E),
            onTertiary             = Color.White,
            tertiaryContainer      = Color(0xFFC8F5D5),
            onTertiaryContainer    = Color(0xFF002111),
            error                  = Color(0xFFBA1A1A),
            onError                = Color.White,
            errorContainer         = Color(0xFFFFDAD6),
            onErrorContainer       = Color(0xFF410002),
            background             = Color(0xFFEEF1FB),
            onBackground           = Color(0xFF1A1C22),
            surface                = Color(0xFFFFFFFF),
            onSurface              = Color(0xFF1A1C22),
            surfaceVariant         = Color(0xFFF3F6FF),
            onSurfaceVariant       = Color(0xFF44474F),
            outline                = Color(0xFFC5C9E0),
            outlineVariant         = Color(0xFFDDE1F5),
            inverseSurface         = Color(0xFF2E3141),
            inverseOnSurface       = Color(0xFFECEEFF),
            inversePrimary         = Color(0xFFAEC6FF),
            surfaceContainerLowest = Color(0xFFF7F9FF),
            surfaceContainerLow    = Color(0xFFEEF1FB),
            surfaceContainer       = Color(0xFFE8EDFF),
            surfaceContainerHigh   = Color(0xFFFFFFFF),
            surfaceContainerHighest= Color(0xFFFFFFFF),
            scrim                  = Color(0xFF000000)
        )

        EMERALD -> lightColorScheme(
            primary                = Color(0xFF00897B),
            onPrimary              = Color.White,
            primaryContainer       = Color(0xFFB2DFDB),
            onPrimaryContainer     = Color(0xFF00251F),
            secondary              = Color(0xFF43A047),
            onSecondary            = Color.White,
            secondaryContainer     = Color(0xFFC8E6C9),
            onSecondaryContainer   = Color(0xFF002105),
            tertiary               = Color(0xFF00796B),
            onTertiary             = Color.White,
            tertiaryContainer      = Color(0xFFB2EBF2),
            onTertiaryContainer    = Color(0xFF002620),
            error                  = Color(0xFFBA1A1A),
            onError                = Color.White,
            errorContainer         = Color(0xFFFFDAD6),
            onErrorContainer       = Color(0xFF410002),
            background             = Color(0xFFF1F8F5),
            onBackground           = Color(0xFF0D1511),
            surface                = Color(0xFFFFFFFF),
            onSurface              = Color(0xFF0D1511),
            surfaceVariant         = Color(0xFFD8EFEA),
            onSurfaceVariant       = Color(0xFF3C4F4A),
            outline                = Color(0xFF9CB5AF),
            outlineVariant         = Color(0xFFBDD8D2),
            inverseSurface         = Color(0xFF1C302A),
            inverseOnSurface       = Color(0xFFEAF3EF),
            inversePrimary         = Color(0xFF80CBC4),
            surfaceContainerLowest = Color(0xFFF5FBF8),
            surfaceContainerLow    = Color(0xFFF1F8F5),
            surfaceContainer       = Color(0xFFDEEEE9),
            surfaceContainerHigh   = Color(0xFFFFFFFF),
            surfaceContainerHighest= Color(0xFFFFFFFF),
            scrim                  = Color(0xFF000000)
        )

        SUNSET -> lightColorScheme(
            primary                = Color(0xFFE64A19),
            onPrimary              = Color.White,
            primaryContainer       = Color(0xFFFFCCBC),
            onPrimaryContainer     = Color(0xFF5C1500),
            secondary              = Color(0xFFF9A825),
            onSecondary            = Color(0xFF1A0F00),
            secondaryContainer     = Color(0xFFFFF3CD),
            onSecondaryContainer   = Color(0xFF241A00),
            tertiary               = Color(0xFF827717),
            onTertiary             = Color.White,
            tertiaryContainer      = Color(0xFFFFF9C4),
            onTertiaryContainer    = Color(0xFF221E00),
            error                  = Color(0xFFBA1A1A),
            onError                = Color.White,
            errorContainer         = Color(0xFFFFDAD6),
            onErrorContainer       = Color(0xFF410002),
            background             = Color(0xFFFDF4EF),
            onBackground           = Color(0xFF1C1410),
            surface                = Color(0xFFFFFFFF),
            onSurface              = Color(0xFF1C1410),
            surfaceVariant         = Color(0xFFF5E6DC),
            onSurfaceVariant       = Color(0xFF534844),
            outline                = Color(0xFFD9BDB5),
            outlineVariant         = Color(0xFFEFD5CC),
            inverseSurface         = Color(0xFF3B2921),
            inverseOnSurface       = Color(0xFFFDF4EF),
            inversePrimary         = Color(0xFFFF8A65),
            surfaceContainerLowest = Color(0xFFFFF8F5),
            surfaceContainerLow    = Color(0xFFFDF4EF),
            surfaceContainer       = Color(0xFFF5E9E3),
            surfaceContainerHigh   = Color(0xFFFFFFFF),
            surfaceContainerHighest= Color(0xFFFFFFFF),
            scrim                  = Color(0xFF000000)
        )

        ROSE -> lightColorScheme(
            primary                = Color(0xFFD81B60),
            onPrimary              = Color.White,
            primaryContainer       = Color(0xFFF8BBD0),
            onPrimaryContainer     = Color(0xFF5C0026),
            secondary              = Color(0xFF8E24AA),
            onSecondary            = Color.White,
            secondaryContainer     = Color(0xFFE1BEE7),
            onSecondaryContainer   = Color(0xFF38004E),
            tertiary               = Color(0xFFAD1457),
            onTertiary             = Color.White,
            tertiaryContainer      = Color(0xFFFFCDD2),
            onTertiaryContainer    = Color(0xFF500021),
            error                  = Color(0xFFBA1A1A),
            onError                = Color.White,
            errorContainer         = Color(0xFFFFDAD6),
            onErrorContainer       = Color(0xFF410002),
            background             = Color(0xFFFDF2F5),
            onBackground           = Color(0xFF1C1214),
            surface                = Color(0xFFFFFFFF),
            onSurface              = Color(0xFF1C1214),
            surfaceVariant         = Color(0xFFF5E4EA),
            onSurfaceVariant       = Color(0xFF524348),
            outline                = Color(0xFFD8B5BF),
            outlineVariant         = Color(0xFFEFCED8),
            inverseSurface         = Color(0xFF3B2328),
            inverseOnSurface       = Color(0xFFFDF2F5),
            inversePrimary         = Color(0xFFF48FB1),
            surfaceContainerLowest = Color(0xFFFFF7F9),
            surfaceContainerLow    = Color(0xFFFDF2F5),
            surfaceContainer       = Color(0xFFF5E7EC),
            surfaceContainerHigh   = Color(0xFFFFFFFF),
            surfaceContainerHighest= Color(0xFFFFFFFF),
            scrim                  = Color(0xFF000000)
        )

        MIDNIGHT -> lightColorScheme(
            primary                = Color(0xFF3949AB),
            onPrimary              = Color.White,
            primaryContainer       = Color(0xFFC5CAE9),
            onPrimaryContainer     = Color(0xFF0D1A6B),
            secondary              = Color(0xFF607D8B),
            onSecondary            = Color.White,
            secondaryContainer     = Color(0xFFCFD8DC),
            onSecondaryContainer   = Color(0xFF1E2E36),
            tertiary               = Color(0xFF455A64),
            onTertiary             = Color.White,
            tertiaryContainer      = Color(0xFFB0BEC5),
            onTertiaryContainer    = Color(0xFF101E26),
            error                  = Color(0xFFBA1A1A),
            onError                = Color.White,
            errorContainer         = Color(0xFFFFDAD6),
            onErrorContainer       = Color(0xFF410002),
            background             = Color(0xFFF2F3F8),
            onBackground           = Color(0xFF121318),
            surface                = Color(0xFFFFFFFF),
            onSurface              = Color(0xFF121318),
            surfaceVariant         = Color(0xFFE3E5F0),
            onSurfaceVariant       = Color(0xFF434454),
            outline                = Color(0xFFB2B5CA),
            outlineVariant         = Color(0xFFCFD0E6),
            inverseSurface         = Color(0xFF292A38),
            inverseOnSurface       = Color(0xFFF2F3F8),
            inversePrimary         = Color(0xFFB0BEC5),
            surfaceContainerLowest = Color(0xFFF8F9FF),
            surfaceContainerLow    = Color(0xFFF2F3F8),
            surfaceContainer       = Color(0xFFE6E8F3),
            surfaceContainerHigh   = Color(0xFFFFFFFF),
            surfaceContainerHighest= Color(0xFFFFFFFF),
            scrim                  = Color(0xFF000000)
        )
    }

    fun darkScheme(): ColorScheme = when (this) {

        CINEMATIC -> darkColorScheme(
            primary                = Color(0xFF80EEFF),
            onPrimary              = Color(0xFF003640),
            primaryContainer       = Color(0xFF004E5C),
            onPrimaryContainer     = Color(0xFF80EEFF),
            secondary              = Color(0xFFFFE082),
            onSecondary            = Color(0xFF3E2C00),
            secondaryContainer     = Color(0xFF5A3F00),
            onSecondaryContainer   = Color(0xFFFFE082),
            tertiary               = Color(0xFFD0BCFF),
            onTertiary             = Color(0xFF370085),
            tertiaryContainer      = Color(0xFF5300BA),
            onTertiaryContainer    = Color(0xFFD0BCFF),
            error                  = Color(0xFFFFB4AB),
            onError                = Color(0xFF690005),
            errorContainer         = Color(0xFF93000A),
            onErrorContainer       = Color(0xFFFFDAD6),
            background             = Color(0xFF0A0C10),
            onBackground           = Color(0xFFDDE3EC),
            surface                = Color(0xFF0F1318),
            onSurface              = Color(0xFFDDE3EC),
            surfaceVariant         = Color(0xFF161B22),
            onSurfaceVariant       = Color(0xFF8896A8),
            outline                = Color(0xFF2A3340),
            outlineVariant         = Color(0xFF1E2733),
            inverseSurface         = Color(0xFFDDE3EC),
            inverseOnSurface       = Color(0xFF0A0C10),
            inversePrimary         = Color(0xFF00BCD4),
            surfaceContainerLowest = Color(0xFF0A0C10),
            surfaceContainerLow    = Color(0xFF0F1318),
            surfaceContainer       = Color(0xFF161B22),
            surfaceContainerHigh   = Color(0xFF1C222C),
            surfaceContainerHighest= Color(0xFF202835),
            scrim                  = Color(0xFF000000)
        )

        BLUE -> darkColorScheme(
            primary                = Color(0xFFAEC6FF),
            onPrimary              = Color(0xFF002E6E),
            primaryContainer       = Color(0xFF004398),
            onPrimaryContainer     = Color(0xFFAEC6FF),
            secondary              = Color(0xFFC5CAE9),
            onSecondary            = Color(0xFF1D2578),
            secondaryContainer     = Color(0xFF2D3691),
            onSecondaryContainer   = Color(0xFFC5CAE9),
            tertiary               = Color(0xFFB9F6CA),
            onTertiary             = Color(0xFF00391D),
            tertiaryContainer      = Color(0xFF00522C),
            onTertiaryContainer    = Color(0xFFB9F6CA),
            error                  = Color(0xFFFFB4AB),
            onError                = Color(0xFF690005),
            errorContainer         = Color(0xFF93000A),
            onErrorContainer       = Color(0xFFFFDAD6),
            background             = Color(0xFF0E1117),
            onBackground           = Color(0xFFE2E5F0),
            surface                = Color(0xFF161B27),
            onSurface              = Color(0xFFE2E5F0),
            surfaceVariant         = Color(0xFF1E2537),
            onSurfaceVariant       = Color(0xFF8D97B2),
            outline                = Color(0xFF3A4660),
            outlineVariant         = Color(0xFF263044),
            inverseSurface         = Color(0xFFE2E5F0),
            inverseOnSurface       = Color(0xFF0E1117),
            inversePrimary         = Color(0xFF1A73E8),
            surfaceContainerLowest = Color(0xFF0E1117),
            surfaceContainerLow    = Color(0xFF161B27),
            surfaceContainer       = Color(0xFF1E2537),
            surfaceContainerHigh   = Color(0xFF222C3F),
            surfaceContainerHighest= Color(0xFF283350),
            scrim                  = Color(0xFF000000)
        )

        EMERALD -> darkColorScheme(
            primary                = Color(0xFF80CBC4),
            onPrimary              = Color(0xFF00251F),
            primaryContainer       = Color(0xFF004D48),
            onPrimaryContainer     = Color(0xFF80CBC4),
            secondary              = Color(0xFFA5D6A7),
            onSecondary            = Color(0xFF002105),
            secondaryContainer     = Color(0xFF1B3E1E),
            onSecondaryContainer   = Color(0xFFA5D6A7),
            tertiary               = Color(0xFF80DEEA),
            onTertiary             = Color(0xFF002620),
            tertiaryContainer      = Color(0xFF004D43),
            onTertiaryContainer    = Color(0xFF80DEEA),
            error                  = Color(0xFFFFB4AB),
            onError                = Color(0xFF690005),
            errorContainer         = Color(0xFF93000A),
            onErrorContainer       = Color(0xFFFFDAD6),
            background             = Color(0xFF0A0F0C),
            onBackground           = Color(0xFFDCE7E2),
            surface                = Color(0xFF0E1511),
            onSurface              = Color(0xFFDCE7E2),
            surfaceVariant         = Color(0xFF151E19),
            onSurfaceVariant       = Color(0xFF7E9A92),
            outline                = Color(0xFF2A3D36),
            outlineVariant         = Color(0xFF1E2E28),
            inverseSurface         = Color(0xFFDCE7E2),
            inverseOnSurface       = Color(0xFF0A0F0C),
            inversePrimary         = Color(0xFF00897B),
            surfaceContainerLowest = Color(0xFF0A0F0C),
            surfaceContainerLow    = Color(0xFF0E1511),
            surfaceContainer       = Color(0xFF151E19),
            surfaceContainerHigh   = Color(0xFF1C2820),
            surfaceContainerHighest= Color(0xFF20302A),
            scrim                  = Color(0xFF000000)
        )

        SUNSET -> darkColorScheme(
            primary                = Color(0xFFFF8A65),
            onPrimary              = Color(0xFF5C1500),
            primaryContainer       = Color(0xFF8C3600),
            onPrimaryContainer     = Color(0xFFFF8A65),
            secondary              = Color(0xFFFFE082),
            onSecondary            = Color(0xFF241A00),
            secondaryContainer     = Color(0xFF4A3800),
            onSecondaryContainer   = Color(0xFFFFE082),
            tertiary               = Color(0xFFE6EE9C),
            onTertiary             = Color(0xFF221E00),
            tertiaryContainer      = Color(0xFF423C00),
            onTertiaryContainer    = Color(0xFFE6EE9C),
            error                  = Color(0xFFFFB4AB),
            onError                = Color(0xFF690005),
            errorContainer         = Color(0xFF93000A),
            onErrorContainer       = Color(0xFFFFDAD6),
            background             = Color(0xFF100C08),
            onBackground           = Color(0xFFECDDD6),
            surface                = Color(0xFF17110D),
            onSurface              = Color(0xFFECDDD6),
            surfaceVariant         = Color(0xFF211916),
            onSurfaceVariant       = Color(0xFFA08A83),
            outline                = Color(0xFF3D2D29),
            outlineVariant         = Color(0xFF2E201C),
            inverseSurface         = Color(0xFFECDDD6),
            inverseOnSurface       = Color(0xFF100C08),
            inversePrimary         = Color(0xFFE64A19),
            surfaceContainerLowest = Color(0xFF100C08),
            surfaceContainerLow    = Color(0xFF17110D),
            surfaceContainer       = Color(0xFF211916),
            surfaceContainerHigh   = Color(0xFF2B221D),
            surfaceContainerHighest= Color(0xFF332924),
            scrim                  = Color(0xFF000000)
        )

        ROSE -> darkColorScheme(
            primary                = Color(0xFFF48FB1),
            onPrimary              = Color(0xFF5C0026),
            primaryContainer       = Color(0xFF880044),
            onPrimaryContainer     = Color(0xFFF48FB1),
            secondary              = Color(0xFFCE93D8),
            onSecondary            = Color(0xFF38004E),
            secondaryContainer     = Color(0xFF601070),
            onSecondaryContainer   = Color(0xFFCE93D8),
            tertiary               = Color(0xFFF06292),
            onTertiary             = Color(0xFF500021),
            tertiaryContainer      = Color(0xFF800040),
            onTertiaryContainer    = Color(0xFFF06292),
            error                  = Color(0xFFFFB4AB),
            onError                = Color(0xFF690005),
            errorContainer         = Color(0xFF93000A),
            onErrorContainer       = Color(0xFFFFDAD6),
            background             = Color(0xFF100A0C),
            onBackground           = Color(0xFFEBDFE3),
            surface                = Color(0xFF170E11),
            onSurface              = Color(0xFFEBDFE3),
            surfaceVariant         = Color(0xFF211519),
            onSurfaceVariant       = Color(0xFF9F8890),
            outline                = Color(0xFF3D2A30),
            outlineVariant         = Color(0xFF2E1E25),
            inverseSurface         = Color(0xFFEBDFE3),
            inverseOnSurface       = Color(0xFF100A0C),
            inversePrimary         = Color(0xFFD81B60),
            surfaceContainerLowest = Color(0xFF100A0C),
            surfaceContainerLow    = Color(0xFF170E11),
            surfaceContainer       = Color(0xFF211519),
            surfaceContainerHigh   = Color(0xFF2C1D23),
            surfaceContainerHighest= Color(0xFF34242B),
            scrim                  = Color(0xFF000000)
        )

        MIDNIGHT -> darkColorScheme(
            primary                = Color(0xFFB0BEC5),
            onPrimary              = Color(0xFF0D1A6B),
            primaryContainer       = Color(0xFF1A2380),
            onPrimaryContainer     = Color(0xFFB0BEC5),
            secondary              = Color(0xFFCFD8DC),
            onSecondary            = Color(0xFF1E2E36),
            secondaryContainer     = Color(0xFF2E4450),
            onSecondaryContainer   = Color(0xFFCFD8DC),
            tertiary               = Color(0xFFB0BEC5),
            onTertiary             = Color(0xFF101E26),
            tertiaryContainer      = Color(0xFF1E3040),
            onTertiaryContainer    = Color(0xFFB0BEC5),
            error                  = Color(0xFFFFB4AB),
            onError                = Color(0xFF690005),
            errorContainer         = Color(0xFF93000A),
            onErrorContainer       = Color(0xFFFFDAD6),
            background             = Color(0xFF08090E),
            onBackground           = Color(0xFFE2E4EC),
            surface                = Color(0xFF0D0E15),
            onSurface              = Color(0xFFE2E4EC),
            surfaceVariant         = Color(0xFF14161F),
            onSurfaceVariant       = Color(0xFF878AA0),
            outline                = Color(0xFF252838),
            outlineVariant         = Color(0xFF1B1D2C),
            inverseSurface         = Color(0xFFE2E4EC),
            inverseOnSurface       = Color(0xFF08090E),
            inversePrimary         = Color(0xFF3949AB),
            surfaceContainerLowest = Color(0xFF08090E),
            surfaceContainerLow    = Color(0xFF0D0E15),
            surfaceContainer       = Color(0xFF14161F),
            surfaceContainerHigh   = Color(0xFF1A1D28),
            surfaceContainerHighest= Color(0xFF202332),
            scrim                  = Color(0xFF000000)
        )
    }
}

/** Companion object helpers */
object AppThemePaletteHelper {
    /**
     * Safely parse a stored string key back to the enum.
     * Defaults to BLUE (Nosved Blue) - the app's factory default palette.
     */
    fun fromKey(key: String?): AppThemePalette =
        AppThemePalette.entries.firstOrNull { it.name == key } ?: AppThemePalette.BLUE
}
